export type ToolKind = "word-counter" | "character-counter" | "case-converter" | "json-formatter" | "json-validator" | "base64";
export type Tool = { slug: ToolKind; name: string; description: string; category: "Text" | "Developer" | "Encoding"; icon: string; keywords: string[]; related: ToolKind[]; example: string; faqs: { question: string; answer: string }[] };

const sharedTextFaq = [{ question: "Is my text uploaded?", answer: "No. This tool processes the text you enter locally in your browser." }];
export const tools: Tool[] = [
  { slug: "word-counter", name: "Word Counter", description: "Count words, characters, sentences and reading time.", category: "Text", icon: "Aa", keywords: ["words", "reading", "essay"], related: ["character-counter", "case-converter"], example: "Paste an essay, note, or draft to see its length instantly.", faqs: [...sharedTextFaq, { question: "What counts as a word?", answer: "Words are groups of characters separated by whitespace." }, { question: "How is reading time calculated?", answer: "It uses an average silent reading pace of 200 words per minute." }] },
  { slug: "character-counter", name: "Character Counter", description: "Measure characters, words and lines in real time.", category: "Text", icon: "123", keywords: ["characters", "text", "social"], related: ["word-counter", "case-converter"], example: "Use it to check a caption, title, bio, or any short text.", faqs: [...sharedTextFaq, { question: "Do spaces count?", answer: "Both totals are shown: including spaces and excluding spaces." }, { question: "Can I use this for social posts?", answer: "Yes. It is useful for checking text against platform limits." }] },
  { slug: "case-converter", name: "Case Converter", description: "Convert text to uppercase, camelCase, snake_case and more.", category: "Text", icon: "aA", keywords: ["uppercase", "camelcase", "snake case"], related: ["word-counter", "character-counter"], example: "Convert “hello world” to Hello World, helloWorld, or HELLO_WORLD.", faqs: [...sharedTextFaq, { question: "Which formats are available?", answer: "Uppercase, lowercase, title, sentence, camel, Pascal, snake and kebab case are included." }, { question: "Is it useful for code?", answer: "Yes. camelCase, PascalCase, snake_case and kebab-case are common naming styles." }] },
  { slug: "json-formatter", name: "JSON Formatter", description: "Format, minify and validate JSON instantly.", category: "Developer", icon: "{}", keywords: ["json", "beautify", "minify"], related: ["json-validator", "base64"], example: "Paste compact JSON and use Format JSON to make its structure easy to read.", faqs: [{ question: "Does this send JSON to a server?", answer: "No. JSON parsing and formatting happen in your browser." }, { question: "What if my JSON is invalid?", answer: "The tool shows a readable error instead of changing your input." }, { question: "What does minify do?", answer: "It removes unnecessary whitespace while keeping the JSON data unchanged." }] },
  { slug: "json-validator", name: "JSON Validator", description: "Check whether JSON is valid and format it when it is.", category: "Developer", icon: "✓", keywords: ["json", "validate", "validator"], related: ["json-formatter", "base64"], example: "Paste JSON from an API response to quickly check its syntax.", faqs: [{ question: "What makes JSON invalid?", answer: "Common issues include missing quotes, trailing commas and unmatched brackets." }, { question: "Can I format valid JSON?", answer: "Yes. Valid JSON can be formatted into readable indentation." }, { question: "Is my data private?", answer: "Yes. Validation runs locally in your browser." }] },
  { slug: "base64", name: "Base64 Encoder / Decoder", description: "Encode text to Base64 or decode Base64 safely.", category: "Encoding", icon: "64", keywords: ["base64", "encode", "decode"], related: ["json-formatter", "json-validator"], example: "Encode plain text for a data payload, or decode a Base64 string back to text.", faqs: [{ question: "Does Base64 encrypt data?", answer: "No. Base64 is an encoding, not encryption, and can be decoded easily." }, { question: "Does it support non-English text?", answer: "Yes. This tool handles UTF-8 text." }, { question: "What happens with invalid Base64?", answer: "The tool shows an error and leaves your input intact." }] },
];
export const toolBySlug = (slug: string) => tools.find((tool) => tool.slug === slug);
