export type TextStats = { words: number; characters: number; charactersWithoutSpaces: number; sentences: number; paragraphs: number; lines: number; readingMinutes: number };
export function getTextStats(input: string): TextStats { const trimmed = input.trim(); return { words: trimmed ? trimmed.split(/\s+/).length : 0, characters: input.length, charactersWithoutSpaces: input.replace(/\s/g, "").length, sentences: trimmed ? (trimmed.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.length ?? 0) : 0, paragraphs: trimmed ? trimmed.split(/\n\s*\n/).filter(Boolean).length : 0, lines: input ? input.split(/\r?\n/).length : 0, readingMinutes: Math.ceil((trimmed ? trimmed.split(/\s+/).length : 0) / 200) }; }
const words = (input: string) => input.trim().split(/[^\p{L}\p{N}]+/u).filter(Boolean);
const title = (input: string) => words(input).map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()).join(" ");
export function convertCase(input: string, type: string) { const parts = words(input); if (!parts.length) return ""; const lower = parts.map((part) => part.toLowerCase()); switch (type) { case "upper": return input.toUpperCase(); case "lower": return input.toLowerCase(); case "title": return title(input); case "sentence": return input.toLowerCase().replace(/(^\s*\p{L}|[.!?]\s+\p{L})/gu, (m) => m.toUpperCase()); case "camel": return lower[0] + lower.slice(1).map((part) => part[0].toUpperCase() + part.slice(1)).join(""); case "pascal": return lower.map((part) => part[0].toUpperCase() + part.slice(1)).join(""); case "snake": return lower.join("_"); case "kebab": return lower.join("-"); default: return input; } }
export function formatJson(input: string, minify = false) { return JSON.stringify(JSON.parse(input), null, minify ? undefined : 2); }
const toBytes = (text: string) => new TextEncoder().encode(text);
export function encodeBase64(input: string) { const bytes = toBytes(input); let binary = ""; bytes.forEach((byte) => binary += String.fromCharCode(byte)); return btoa(binary); }
export function decodeBase64(input: string) { const clean = input.replace(/\s/g, ""); if (!clean || !/^[A-Za-z0-9+/]*={0,2}$/.test(clean) || clean.length % 4 === 1) throw new Error("Please enter valid Base64 text."); const binary = atob(clean); return new TextDecoder().decode(Uint8Array.from(binary, (char) => char.charCodeAt(0))); }
