import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ToolWorkspace } from "@/components/tool-workspace";
import { toolBySlug, tools } from "@/lib/tools";

export function generateStaticParams() { return tools.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const tool = toolBySlug(slug); if (!tool) return {}; return { title: tool.name, description: tool.description, alternates: { canonical: `/tools/${tool.slug}` }, openGraph: { title: `${tool.name} | KnightWisdom Tools`, description: tool.description } }; }); }
export default async function ToolPage({ params }: { params: Promise<{ slug: string }> }) { const tool = toolBySlug((await params).slug); if (!tool) notFound(); const related = tool.related.map((slug) => toolBySlug(slug)).filter(Boolean); return <main className="tool-page"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Tools</Link><span>/</span><span>{tool.name}</span></nav><header className="tool-hero"><p className="eyebrow">{tool.category}</p><h1>{tool.name}</h1><p>{tool.description}</p><span>✦ Processed locally in your browser</span></header><ToolWorkspace tool={tool}/><section className="content-grid"><article><h2>How to use {tool.name}</h2><ol><li>Paste or type your content into the input area.</li><li>Choose the action that fits your task.</li><li>Copy the result when you are ready.</li></ol><h2>Example</h2><p>{tool.example}</p></article><aside><h2>Frequently asked questions</h2>{tool.faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</aside></section><section className="related"><p className="eyebrow">KEEP EXPLORING</p><h2>Related tools</h2><div className="related-links">{related.map((item) => item && <Link href={`/tools/${item.slug}`} key={item.slug}>{item.name}<span>{item.description}</span></Link>)}</div></section></main>; }
