"use client";

import { ChangeEvent, DragEvent, PointerEvent, useEffect, useMemo, useRef, useState } from "react";
import fontkit from "@pdf-lib/fontkit";
import { degrees, PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { ArrowRight } from "@/components/icons";
import { commitEditorHistory, copyElement, createEditorHistory, createEditorId, EditorPage, moveElement, pagePointToRotatedViewport, PdfEditorElement, PdfEditorElementType, redoEditorHistory, removeEditorPage, removeElement, reorderEditorPage, reorderElement, resizeElement, rotateEditorPage, rotatedViewportToPagePoint, topLeftToPdfLibY, undoEditorHistory, viewportToPdfPoint } from "@/lib/pdf-editor";

type Language = "en" | "zh-CN";
type Tool = "select" | PdfEditorElementType;
type PdfJsDocument = { numPages: number; getPage: (page: number) => Promise<any>; destroy?: () => Promise<void> | void };
type Result = { url: string; name: string; size: number; pages: number };
const MAX_SIZE = 20 * 1024 * 1024;
const cjk = /[\u3400-\u9fff]/;

const messages = {
  en: { navigation: { blog: "Blog", computer: "Computer tools", pdf: "PDF", images: "Image tools", business: "Business tools" }, languageLabel: "Choose language", back: "All tools", label: "PDF EDITOR", title: "Edit PDF, privately in your browser.", intro: "Every edit is made locally. Add content, arrange pages, then export only when you are ready.", drop: "Drop a PDF here to begin", choose: "Open PDF", hint: "PDF files up to 20 MB", privacy: "Your file is processed locally in your browser and is never uploaded to our server.", opening: "Opening PDF…", error: "We could not open this PDF. It may be encrypted, damaged, or unsupported.", tooLarge: "Please choose a PDF smaller than 20 MB.", done: "Complete editing", processing: "Creating your edited PDF…", result: "PDF editing complete", resultText: "Your result is ready. Nothing has downloaded automatically.", download: "Download edited PDF", continue: "Continue editing", newFile: "Choose another file", properties: "Properties", elements: "Elements", none: "Select an item on the page to edit it.", page: "Page", pages: "pages", font: "Font", fontSize: "Size", color: "Colour", fill: "Fill", opacity: "Opacity", width: "Width", height: "Height", stroke: "Stroke", line: "Line", lock: "Lock", hide: "Hide", clear: "Clear this page", rotate: "Rotate", deletePage: "Delete page", copyPage: "Duplicate page", fontHint: "For Chinese text, upload a TTF or OTF font once before export.", cjkError: "To export Chinese text, upload a TTF or OTF font in Properties.", footer: { tagline: "Thoughtful tools and ideas for a more capable day.", rights: "All rights reserved.", privacy: "Privacy", terms: "Terms", contact: "Contact" } },
  "zh-CN": { navigation: { blog: "博客", computer: "计算机工具", pdf: "PDF", images: "图片工具", business: "商业工具" }, languageLabel: "选择语言", back: "全部工具", label: "PDF 在线编辑器", title: "在浏览器中私密编辑 PDF。", intro: "所有编辑均在本地完成。添加内容、调整页面，并在准备好后导出。", drop: "将 PDF 拖到这里开始", choose: "打开 PDF", hint: "支持最大 20 MB 的 PDF 文件", privacy: "您的文件仅在浏览器本地处理，绝不会上传到我们的服务器。", opening: "正在打开 PDF…", error: "无法打开此 PDF。它可能已加密、损坏或不受支持。", tooLarge: "请选择小于 20 MB 的 PDF。", done: "完成编辑", processing: "正在生成编辑后的 PDF…", result: "PDF 编辑完成", resultText: "文件已准备好，不会自动下载。", download: "下载编辑后的 PDF", continue: "继续编辑", newFile: "重新选择文件", properties: "属性", elements: "元素", none: "请选择页面上的元素以编辑它。", page: "第", pages: "页", font: "字体", fontSize: "字号", color: "颜色", fill: "填充", opacity: "透明度", width: "宽度", height: "高度", stroke: "描边", line: "线条", lock: "锁定", hide: "隐藏", clear: "清除此页", rotate: "旋转", deletePage: "删除页面", copyPage: "复制页面", fontHint: "导出中文文字前，请上传一次 TTF 或 OTF 字体。", cjkError: "如需导出中文文字，请在属性栏上传 TTF 或 OTF 字体。", footer: { tagline: "让每一天都更有能力的实用工具与想法。", rights: "保留所有权利。", privacy: "隐私", terms: "条款", contact: "联系" } },
} as const;
const labels = { en: { select: "Select", text: "Text", image: "Image", draw: "Draw", highlight: "Highlight", rectangle: "Rectangle", ellipse: "Circle", line: "Line", arrow: "Arrow", signature: "Signature", comment: "Comment", undo: "Undo", redo: "Redo", delete: "Delete", duplicate: "Copy", forward: "Forward", backward: "Backward", top: "To top", bottom: "To bottom", fit: "Fit page", zoomOut: "Zoom out", zoomIn: "Zoom in" }, "zh-CN": { select: "选择", text: "文字", image: "图片", draw: "画笔", highlight: "高亮", rectangle: "矩形", ellipse: "圆形", line: "直线", arrow: "箭头", signature: "签名", comment: "注释", undo: "撤销", redo: "重做", delete: "删除", duplicate: "复制", forward: "前移", backward: "后移", top: "置顶", bottom: "置底", fit: "适应页面", zoomOut: "缩小", zoomIn: "放大" } } as const;
const baseName = (name: string) => name.replace(/\.pdf$/i, "");
const toRgb = (hex = "#FF4FA3") => rgb(parseInt(hex.slice(1, 3), 16) / 255, parseInt(hex.slice(3, 5), 16) / 255, parseInt(hex.slice(5, 7), 16) / 255);
const dataToBytes = async (data: string) => fetch(data).then((response) => response.arrayBuffer());

export function PdfEditorPage() {
  const [language, setLanguage] = useState<Language>("en"); const t = messages[language]; const l = labels[language];
  const [file, setFile] = useState<File | null>(null); const [bytes, setBytes] = useState<Uint8Array | null>(null); const [pdf, setPdf] = useState<PdfJsDocument | null>(null);
  const [pages, setPages] = useState<EditorPage[]>([]); const [current, setCurrent] = useState(0); const [sourceSize, setSourceSize] = useState({ width: 595, height: 842 }); const [viewSize, setViewSize] = useState({ width: 595, height: 842 }); const [zoom, setZoom] = useState(1);
  const [history, setHistory] = useState(() => createEditorHistory()); const elements = history.present; const [selectedId, setSelectedId] = useState<string | null>(null); const selected = elements.find((item) => item.id === selectedId) ?? null;
  const [tool, setTool] = useState<Tool>("select"); const [panel, setPanel] = useState<"properties" | "elements">("properties"); const [collapsed, setCollapsed] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<Result | null>(null);
  const [imageData, setImageData] = useState<string | null>(null); const [fontBytes, setFontBytes] = useState<Uint8Array | null>(null); const [dirty, setDirty] = useState(false);
  const canvas = useRef<HTMLCanvasElement>(null); const shell = useRef<HTMLDivElement>(null); const fileInput = useRef<HTMLInputElement>(null); const drawing = useRef<{ element: PdfEditorElement; base: PdfEditorElement[] } | null>(null); const drag = useRef<{ id: string; base: PdfEditorElement[]; x: number; y: number; ox: number; oy: number } | null>(null); const resizing = useRef<{ id: string; base: PdfEditorElement[]; x: number; y: number; width: number; height: number } | null>(null); const raf = useRef<number | null>(null);
  const activePage = pages[current]; const sourceIndex = activePage?.sourceIndex ?? 0; const rotation = activePage?.rotation ?? 0; const visible = useMemo(() => elements.filter((item) => item.pageIndex === sourceIndex && item.visible !== false), [elements, sourceIndex]);

  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("lang"); const saved = localStorage.getItem("knightwisdom-language") as Language | null; const initial = requested === "en" || requested === "zh-CN" ? requested : saved ?? (navigator.language.toLowerCase().startsWith("zh") ? "zh-CN" : "en"); document.documentElement.lang = initial; setLanguage(initial); }, []);
  useEffect(() => () => { void pdf?.destroy?.(); if (result) URL.revokeObjectURL(result.url); }, [pdf, result]);
  useEffect(() => { const leave = (event: BeforeUnloadEvent) => { if (dirty && !result) { event.preventDefault(); event.returnValue = ""; } }; addEventListener("beforeunload", leave); return () => removeEventListener("beforeunload", leave); }, [dirty, result]);
  useEffect(() => { const keyboard = (event: KeyboardEvent) => { if (!selected || (event.target as HTMLElement)?.matches("input,textarea")) return; if (event.key === "Delete" || event.key === "Backspace") { event.preventDefault(); removeSelected(); } const change = event.shiftKey ? 10 : 1; const direction: Record<string, [number, number]> = { ArrowLeft: [-change, 0], ArrowRight: [change, 0], ArrowUp: [0, -change], ArrowDown: [0, change] }; if (direction[event.key]) { event.preventDefault(); mutate(elements.map((item) => item.id === selected.id ? moveElement(item, ...direction[event.key]) : item)); } }; addEventListener("keydown", keyboard); return () => removeEventListener("keydown", keyboard); });

  const changeLanguage = (next: Language) => { localStorage.setItem("knightwisdom-language", next); document.documentElement.lang = next; window.history.replaceState(null, "", `${location.pathname}?lang=${next}`); setLanguage(next); };
  const mutate = (next: PdfEditorElement[]) => { setHistory((previous) => commitEditorHistory(previous, next)); setDirty(true); };
  const previewMutate = (next: PdfEditorElement[]) => setHistory((previous) => ({ ...previous, present: next }));
  const update = (id: string, patch: Partial<PdfEditorElement>, commit = false) => { const next = elements.map((item) => item.id === id ? { ...item, ...patch } : item); commit ? mutate(next) : previewMutate(next); };
  const readFile = (next: File) => new Promise<string>((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(next); });
  const normaliseImage = async (next: File) => { const source = await readFile(next); if (next.type !== "image/webp") return source; const image = new Image(); image.src = source; await image.decode(); const convert = document.createElement("canvas"); convert.width = image.naturalWidth; convert.height = image.naturalHeight; convert.getContext("2d")?.drawImage(image, 0, 0); return convert.toDataURL("image/png"); };
  const open = async (next: File | null) => { if (!next) return; if (next.size > MAX_SIZE) { setError(t.tooLarge); return; } setLoading(true); setError(""); try { const data = new Uint8Array(await next.arrayBuffer()); await PDFDocument.load(data, { ignoreEncryption: false }); const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs"); pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs", import.meta.url).toString(); const opened = await pdfjs.getDocument({ data: data.slice() }).promise as unknown as PdfJsDocument; await pdf?.destroy?.(); setFile(next); setBytes(data); setPdf(opened); setPages(Array.from({ length: opened.numPages }, (_, sourceIndex) => ({ sourceIndex, rotation: 0 }))); setCurrent(0); setHistory(createEditorHistory()); setDirty(false); setSelectedId(null); } catch { setError(t.error); } finally { setLoading(false); } };
  useEffect(() => { let cancelled = false; void (async () => { if (!pdf || !canvas.current || !activePage) return; const page = await pdf.getPage(sourceIndex + 1); const base = page.getViewport({ scale: 1, rotation: 0 }); const viewport = page.getViewport({ scale: zoom, rotation }); if (cancelled || !canvas.current) return; canvas.current.width = Math.ceil(viewport.width); canvas.current.height = Math.ceil(viewport.height); setSourceSize({ width: base.width, height: base.height }); setViewSize({ width: viewport.width / zoom, height: viewport.height / zoom }); await page.render({ canvasContext: canvas.current.getContext("2d")!, viewport }).promise; })().catch(() => setError(t.error)); return () => { cancelled = true; }; }, [pdf, sourceIndex, rotation, zoom, activePage, t.error]);
  const pointer = (event: PointerEvent<HTMLElement>) => { const rect = shell.current?.getBoundingClientRect(); const raw = viewportToPdfPoint(event.clientX - (rect?.left ?? 0), event.clientY - (rect?.top ?? 0), zoom); return rotatedViewportToPagePoint(raw.x, raw.y, sourceSize.width, sourceSize.height, rotation); };
  const add = (item: PdfEditorElement) => { mutate([...elements, item]); setSelectedId(item.id); setPanel("properties"); };
  const start = (event: PointerEvent<HTMLDivElement>) => { if (!pdf) return; if (tool === "select") { setSelectedId(null); return; } const point = pointer(event); const id = createEditorId();
    if (tool === "text") add({ id, pageIndex: sourceIndex, type: "text", x: point.x, y: point.y, width: 190, height: 34, text: language === "zh-CN" ? "输入文字" : "Type here", label: "Text", fontSize: 16, color: "#FF4FA3", opacity: 1, lineHeight: 1.35, align: "left" });
    if (tool === "comment") add({ id, pageIndex: sourceIndex, type: "comment", x: point.x, y: point.y, width: 176, height: 74, text: language === "zh-CN" ? "注释" : "Comment", label: "Comment", color: "#FF8DC5", opacity: 1 });
    if (tool === "image" || tool === "signature") { if (!imageData) { setError(language === "zh-CN" ? "请先从工具栏选择图片。" : "Choose an image from the toolbar first."); return; } add({ id, pageIndex: sourceIndex, type: tool, x: point.x, y: point.y, width: 155, height: 90, imageData, label: tool === "signature" ? "Signature" : "Image", opacity: 1 }); return; }
    if (["draw", "highlight", "rectangle", "ellipse", "line", "arrow"].includes(tool)) { const item: PdfEditorElement = tool === "draw" ? { id, pageIndex: sourceIndex, type: "draw", x: point.x, y: point.y, points: [point.x, point.y], color: "#FF4FA3", strokeWidth: 2.5, opacity: 1, label: "Drawing" } : { id, pageIndex: sourceIndex, type: tool, x: point.x, y: point.y, width: 1, height: 1, color: tool === "highlight" ? "#FFD86B" : "#FF4FA3", fillColor: tool === "highlight" ? "#FFD86B" : "#000000", opacity: tool === "highlight" ? .35 : 1, strokeWidth: tool === "highlight" ? 1 : 2, label: tool }; drawing.current = { element: item, base: elements }; previewMutate([...elements, item]); setSelectedId(id); event.currentTarget.setPointerCapture(event.pointerId); }
  };
  const move = (event: PointerEvent<HTMLDivElement>) => { if (raf.current) cancelAnimationFrame(raf.current); raf.current = requestAnimationFrame(() => { const point = pointer(event); if (drawing.current) { const item = drawing.current.element; const patch = item.type === "draw" ? { points: [...(item.points ?? []), point.x, point.y] } : { width: point.x - item.x, height: point.y - item.y }; drawing.current.element = { ...item, ...patch }; previewMutate(elements.map((value) => value.id === item.id ? { ...value, ...patch } : value)); } const active = drag.current; if (active) previewMutate(elements.map((item) => item.id === active.id ? moveElement(item, point.x - active.x + active.ox, point.y - active.y + active.oy) : item)); const resize = resizing.current; if (resize) previewMutate(elements.map((item) => item.id === resize.id ? resizeElement(item, point.x - resize.x + resize.width, point.y - resize.y + resize.height) : item)); }); };
  const end = () => { if (drawing.current) { const base = drawing.current.base; setHistory((previous) => ({ past: [...previous.past, base], present: previous.present, future: [] })); drawing.current = null; setDirty(true); } if (drag.current) { const base = drag.current.base; setHistory((previous) => ({ past: [...previous.past, base], present: previous.present, future: [] })); drag.current = null; setDirty(true); } if (resizing.current) { const base = resizing.current.base; setHistory((previous) => ({ past: [...previous.past, base], present: previous.present, future: [] })); resizing.current = null; setDirty(true); } };
  const selectItem = (event: PointerEvent<HTMLDivElement>, item: PdfEditorElement) => { if (tool !== "select" || item.locked) return; event.stopPropagation(); const point = pointer(event); drag.current = { id: item.id, base: elements, x: point.x, y: point.y, ox: item.x, oy: item.y }; setSelectedId(item.id); setPanel("properties"); event.currentTarget.setPointerCapture(event.pointerId); };
  const resizeItem = (event: PointerEvent<HTMLButtonElement>, item: PdfEditorElement) => { event.stopPropagation(); const point = pointer(event); resizing.current = { id: item.id, base: elements, x: point.x, y: point.y, width: item.width ?? 40, height: item.height ?? 30 }; event.currentTarget.setPointerCapture(event.pointerId); };
  const removeSelected = () => { if (selected) { mutate(removeElement(elements, selected.id)); setSelectedId(null); } };
  const selectImage = async (event: ChangeEvent<HTMLInputElement>) => { const next = event.target.files?.[0]; if (!next || !/image\/(png|jpeg|webp)/.test(next.type)) { setError("Please choose a PNG, JPG, JPEG, or WebP image."); return; } setImageData(await normaliseImage(next)); };
  const pageOperation = (action: "rotate" | "delete" | "copy", index = sourceIndex) => { if (action === "rotate") { setPages((currentPages) => rotateEditorPage(currentPages, index)); setDirty(true); } if (action === "delete") { if (pages.length < 2) { setError(language === "zh-CN" ? "至少保留一页。" : "A PDF must keep at least one page."); return; } setPages((currentPages) => removeEditorPage(currentPages, index)); setCurrent((value) => Math.min(value, pages.length - 2)); setDirty(true); } if (action === "copy") { const position = pages.findIndex((page) => page.sourceIndex === index); setPages((currentPages) => [...currentPages.slice(0, position + 1), { sourceIndex: index, rotation: 0 }, ...currentPages.slice(position + 1)]); setDirty(true); } };
  const exportPdf = async () => { if (!bytes || !file) return; setLoading(true); setError(""); try { const source = await PDFDocument.load(bytes.slice()); const output = await PDFDocument.create(); output.registerFontkit(fontkit); const needsChinese = elements.some((item) => item.type === "text" && cjk.test(item.text ?? "")); if (needsChinese && !fontBytes) throw new Error(t.cjkError); const custom = fontBytes ? await output.embedFont(fontBytes) : null;
      for (const pageRecord of pages) { const [target] = await output.copyPages(source, [pageRecord.sourceIndex]); output.addPage(target); if (pageRecord.rotation) target.setRotation(degrees(pageRecord.rotation)); const size = target.getSize(); const pageItems = elements.filter((item) => item.pageIndex === pageRecord.sourceIndex && item.visible !== false); for (const item of pageItems) await writeElement(output, target, item, size.width, size.height, custom); }
      const saved = await output.save(); const url = URL.createObjectURL(new Blob([saved.buffer as ArrayBuffer], { type: "application/pdf" })); setResult({ url, name: `${baseName(file.name)}-edited.pdf`, size: saved.byteLength, pages: output.getPageCount() }); setDirty(false);
    } catch (reason) { setError(reason instanceof Error ? reason.message : t.error); } finally { setLoading(false); } };
  const reset = () => { result && URL.revokeObjectURL(result.url); setResult(null); setFile(null); setBytes(null); void pdf?.destroy?.(); setPdf(null); setPages([]); setHistory(createEditorHistory()); setDirty(false); };
  if (result) return <main id="top"><Header language={language} onLanguageChange={changeLanguage} copy={{ navigation: t.navigation, languageLabel: t.languageLabel }} /><section className="conversion-result section-shell"><span className="result-check">✓</span><p className="label">PDF EDITOR</p><h1>{t.result}</h1><p>{result.name}<br />{(result.size / 1024 / 1024).toFixed(2)} MB · {result.pages} {t.pages}</p><a className="button button-primary" href={result.url} download={result.name}>{t.download} <ArrowRight /></a><button className="result-reset" onClick={() => setResult(null)}>{t.continue}</button><button className="result-reset" onClick={reset}>{t.newFile}</button></section><Footer copy={t.footer} /></main>;
  const tools: [Tool, string][] = [["select", l.select], ["text", l.text], ["image", l.image], ["draw", l.draw], ["highlight", l.highlight], ["rectangle", l.rectangle], ["ellipse", l.ellipse], ["line", l.line], ["arrow", l.arrow], ["signature", l.signature], ["comment", l.comment]];
  return <main id="top"><Header language={language} onLanguageChange={changeLanguage} copy={{ navigation: t.navigation, languageLabel: t.languageLabel }} /><section className="pdf-editor section-shell"><a className="back-link" href={`/?lang=${language}#tools`}>← {t.back}</a><p className="label">{t.label}</p><h1>{t.title}</h1><p className="converter-intro">{t.intro}</p>{!pdf && <label className="upload-panel editor-upload" onDragOver={(event) => event.preventDefault()} onDrop={(event: DragEvent<HTMLLabelElement>) => { event.preventDefault(); void open(event.dataTransfer.files[0] ?? null); }}><input ref={fileInput} type="file" accept="application/pdf,.pdf" onChange={(event) => void open(event.target.files?.[0] ?? null)} /><span className="upload-icon">↑</span><strong>{t.drop}</strong><span>{t.hint}</span><em>{t.choose}</em></label>}{loading && <p className="editor-status">{t.opening}</p>}{error && <p className="converter-error">{error}</p>}{pdf && <div className={`editor-workspace advanced ${collapsed ? "thumbs-collapsed" : ""}`}>
    <div className="editor-toolbar" role="toolbar" aria-label="PDF editor tools">{tools.map(([next, label]) => (next === "image" || next === "signature") ? <label key={next} title={label} className={`editor-tool ${tool === next ? "active" : ""}`}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { void selectImage(event); setTool(next); }} />{label}</label> : <button key={next} title={label} className={`editor-tool ${tool === next ? "active" : ""}`} onClick={() => setTool(next)} aria-pressed={tool === next}>{label}</button>)}<span className="toolbar-spacer" />{(["undo", "redo", "delete", "duplicate", "backward", "forward", "bottom", "top"] as const).map((action) => <button key={action} title={l[action]} className="editor-tool" disabled={(action === "undo" && !history.past.length) || (action === "redo" && !history.future.length) || (!selected && !["undo", "redo"].includes(action))} onClick={() => { if (action === "undo") setHistory((value) => undoEditorHistory(value)); else if (action === "redo") setHistory((value) => redoEditorHistory(value)); else if (action === "delete") removeSelected(); else if (action === "duplicate" && selected) { const next = copyElement(elements, selected.id); mutate(next); setSelectedId(next.at(-1)?.id ?? null); } else if (selected) mutate(reorderElement(elements, selected.id, action as "forward" | "backward" | "top" | "bottom")); }}>{l[action]}</button>)}<button className="button button-primary editor-download" onClick={() => void exportPdf()} disabled={loading}>{loading ? t.processing : t.done}</button></div>
    <aside className="editor-thumbnails" aria-label="PDF pages"><button className="thumb-collapse" onClick={() => setCollapsed((value) => !value)} aria-label="Toggle thumbnails">{collapsed ? "›" : "‹"}</button>{!collapsed && pages.map((page, index) => <EditorThumbnail key={`${page.sourceIndex}-${index}`} pdf={pdf} page={page} index={index} active={current === index} onClick={() => setCurrent(index)} onDragStart={(event) => event.dataTransfer.setData("text/plain", String(index))} onDrop={(event) => { const from = Number(event.dataTransfer.getData("text/plain")); setPages((value) => reorderEditorPage(value, pages[from]?.sourceIndex ?? page.sourceIndex, index)); }} label={`${t.page} ${index + 1}`} />)}</aside>
    <div className="editor-stage"><div className="editor-page-wrap" ref={shell} style={{ width: viewSize.width * zoom, height: viewSize.height * zoom }} onPointerDown={start} onPointerMove={move} onPointerUp={end}><canvas ref={canvas} /><div className="editor-overlay">{visible.map((item) => <OverlayItem key={item.id} item={item} selected={item.id === selectedId} zoom={zoom} sourceSize={sourceSize} rotation={rotation} onPointerDown={(event) => selectItem(event, item)} onResize={(event) => resizeItem(event, item)} onTextChange={(value) => update(item.id, { text: value })} onTextCommit={() => mutate(elements)} />)}</div></div><div className="editor-bottom"><button className="editor-tool" onClick={() => setZoom((value) => Math.max(.45, value - .15))}>−</button><span>{t.page} {current + 1} / {pages.length} · {Math.round(zoom * 100)}%</span><button className="editor-tool" onClick={() => setZoom((value) => Math.min(2.4, value + .15))}>+</button><button className="editor-tool" onClick={() => setZoom(Math.min(1.25, Math.max(.45, (shell.current?.parentElement?.clientWidth ?? 760) / Math.max(viewSize.width, 1))))}>{l.fit}</button></div></div>
    <aside className="editor-properties"><div className="property-tabs"><button className={panel === "properties" ? "active" : ""} onClick={() => setPanel("properties")}>{t.properties}</button><button className={panel === "elements" ? "active" : ""} onClick={() => setPanel("elements")}>{t.elements}</button></div>{panel === "properties" ? <Properties item={selected} t={t} onChange={(patch) => selected && update(selected.id, patch)} onCommit={() => selected && mutate(elements)} onDelete={removeSelected} onFont={async (event) => { const next = event.target.files?.[0]; if (next) setFontBytes(new Uint8Array(await next.arrayBuffer())); }} /> : <ElementList items={elements.filter((item) => item.pageIndex === sourceIndex)} allItems={elements} selectedId={selectedId} onSelect={setSelectedId} onMutate={mutate} />}</aside>
    <div className="page-actions"><button onClick={() => pageOperation("rotate")}>{t.rotate}</button><button onClick={() => pageOperation("copy")}>{t.copyPage}</button><button onClick={() => pageOperation("delete")}>{t.deletePage}</button><button onClick={() => { mutate(elements.filter((item) => item.pageIndex !== sourceIndex)); setSelectedId(null); }}>{t.clear}</button></div>
  </div>}<p className="converter-privacy">{t.privacy}</p></section><Footer copy={t.footer} /></main>;
}

export async function writeElement(document: PDFDocument, page: any, item: PdfEditorElement, width: number, height: number, customFont: any) { const color = toRgb(item.color); const opacity = item.opacity ?? 1; const w = Math.abs(item.width ?? 1); const h = Math.abs(item.height ?? 1); const x = item.width && item.width < 0 ? item.x + item.width : item.x; const top = item.height && item.height < 0 ? item.y + item.height : item.y; const y = topLeftToPdfLibY(height, top, h); const stroke = item.strokeWidth ?? 2;
  if (item.type === "text") { const font = customFont ?? await document.embedFont(item.fontFamily === "serif" ? StandardFonts.TimesRoman : item.fontFamily === "mono" ? StandardFonts.Courier : StandardFonts.Helvetica); const size = item.fontSize ?? 16; const words = (item.text ?? "").split(/\s+/); const lines: string[] = []; let line = ""; for (const word of words) { const next = line ? `${line} ${word}` : word; if (font.widthOfTextAtSize(next, size) > w && line) { lines.push(line); line = word; } else line = next; } lines.push(line); lines.forEach((lineText, index) => { const textWidth = font.widthOfTextAtSize(lineText, size); const tx = item.align === "center" ? x + (w - textWidth) / 2 : item.align === "right" ? x + w - textWidth : x; const ty = topLeftToPdfLibY(height, top + index * size * (item.lineHeight ?? 1.35), size); page.drawText(lineText, { x: tx, y: ty, size, font, color, opacity }); if (item.underline) page.drawLine({ start: { x: tx, y: ty - 2 }, end: { x: tx + textWidth, y: ty - 2 }, thickness: 1, color, opacity }); }); }
  if (item.type === "rectangle" || item.type === "highlight" || item.type === "comment") page.drawRectangle({ x, y, width: w, height: h, color: item.type === "highlight" ? toRgb(item.fillColor ?? "#FFD86B") : undefined, borderColor: item.type === "highlight" ? undefined : color, borderWidth: stroke, opacity });
  if (item.type === "ellipse") page.drawEllipse({ x: x + w / 2, y: y + h / 2, xScale: w / 2, yScale: h / 2, borderColor: color, borderWidth: stroke, color: item.fillColor && item.fillColor !== "#000000" ? toRgb(item.fillColor) : undefined, opacity });
  if (item.type === "line" || item.type === "arrow") { page.drawLine({ start: { x, y: topLeftToPdfLibY(height, top) }, end: { x: x + (item.width ?? 1), y: topLeftToPdfLibY(height, top + (item.height ?? 1)) }, thickness: stroke, color, opacity }); if (item.type === "arrow") { const ex = x + (item.width ?? 1); const ey = topLeftToPdfLibY(height, top + (item.height ?? 1)); page.drawLine({ start: { x: ex, y: ey }, end: { x: ex - 8, y: ey + 4 }, thickness: stroke, color, opacity }); page.drawLine({ start: { x: ex, y: ey }, end: { x: ex - 8, y: ey - 4 }, thickness: stroke, color, opacity }); } }
  if (item.type === "draw") { const points = item.points ?? []; for (let i = 0; i < points.length - 2; i += 2) page.drawLine({ start: { x: points[i], y: height - points[i + 1] }, end: { x: points[i + 2], y: height - points[i + 3] }, thickness: stroke, color, opacity }); }
  if ((item.type === "image" || item.type === "signature") && item.imageData) { const data = await dataToBytes(item.imageData); const image = item.imageData.startsWith("data:image/png") ? await document.embedPng(data) : await document.embedJpg(data); page.drawImage(image, { x, y, width: w, height: h, opacity, rotate: item.rotation ? degrees(item.rotation) : undefined }); }
  if (item.type === "comment") { const font = customFont ?? await document.embedFont(StandardFonts.Helvetica); page.drawText(item.text ?? "", { x: x + 7, y: y + h - 18, size: 11, font, color: rgb(0.08, 0.08, 0.1), opacity }); }
}

function OverlayItem({ item, selected, zoom, sourceSize, rotation, onPointerDown, onResize, onTextChange, onTextCommit }: { item: PdfEditorElement; selected: boolean; zoom: number; sourceSize: { width: number; height: number }; rotation: EditorPage["rotation"]; onPointerDown: (event: PointerEvent<HTMLDivElement>) => void; onResize: (event: PointerEvent<HTMLButtonElement>) => void; onTextChange: (value: string) => void; onTextCommit: () => void }) { const point = pagePointToRotatedViewport(item.x, item.y, sourceSize.width, sourceSize.height, rotation); const style = { left: point.x * zoom, top: point.y * zoom, width: Math.max(8, Math.abs(item.width ?? 130)) * zoom, height: Math.max(8, Math.abs(item.height ?? 32)) * zoom, opacity: item.opacity ?? 1, transform: `rotate(${(item.rotation ?? 0) + rotation}deg)` };
  if (item.type === "draw") { const points = item.points ?? []; const projected = points.reduce<string>((value, pointValue, index) => { if (index % 2) return `${value},${pointValue * zoom}`; return `${value} ${pointValue * zoom}`; }, ""); return <svg className="pdf-overlay-item pdf-draw" style={{ left: 0, top: 0, width: "100%", height: "100%", pointerEvents: "none" }}><polyline points={projected} fill="none" stroke={item.color} strokeWidth={(item.strokeWidth ?? 2) * zoom} /></svg>; }
  const className = `pdf-overlay-item overlay-${item.type} ${selected ? "selected" : ""}`; const content = item.type === "text" ? <div className="overlay-text-input" contentEditable={selected} suppressContentEditableWarning onInput={(event) => onTextChange(event.currentTarget.textContent ?? "")} onBlur={onTextCommit}>{item.text}</div> : item.type === "comment" ? <><b>●</b>{item.text}</> : item.type === "image" || item.type === "signature" ? <img src={item.imageData} alt={item.label ?? item.type} /> : null;
  return <div className={className} style={{ ...style, color: item.color, borderColor: item.color, background: item.type === "highlight" ? item.fillColor : item.fillColor !== "#000000" ? item.fillColor : undefined, fontSize: (item.fontSize ?? 15) * zoom, textAlign: item.align }} onPointerDown={onPointerDown}>{content}{selected && <><span className="selection-rotate" aria-hidden="true">↻</span><button className="selection-resize" aria-label="Resize element" onPointerDown={onResize} /></>}</div>;
}

type PropertyCopy = { none: string; font: string; fontSize: string; color: string; fill: string; opacity: string; width: string; height: string; deletePage: string; fontHint: string };
function Properties({ item, t, onChange, onCommit, onDelete, onFont }: { item: PdfEditorElement | null; t: PropertyCopy; onChange: (patch: Partial<PdfEditorElement>) => void; onCommit: () => void; onDelete: () => void; onFont: (event: ChangeEvent<HTMLInputElement>) => void }) { if (!item) return <div className="property-empty"><p>{t.none}</p><label>{t.font}<input type="file" accept=".ttf,.otf,font/ttf,font/otf" onChange={onFont} /><small>{t.fontHint}</small></label></div>; const set = (key: keyof PdfEditorElement, value: string | number | boolean) => onChange({ [key]: value }); return <div className="property-form">{item.type === "text" || item.type === "comment" ? <label>Text<textarea value={item.text ?? ""} onChange={(event) => set("text", event.target.value)} onBlur={onCommit} /></label> : null}{item.type === "text" && <><label>{t.font}<select value={item.fontFamily ?? "sans"} onChange={(event) => set("fontFamily", event.target.value)}><option value="sans">Sans</option><option value="serif">Serif</option><option value="mono">Mono</option></select></label><label>{t.fontSize}<input type="number" min="8" max="96" value={item.fontSize ?? 16} onChange={(event) => set("fontSize", Number(event.target.value))} onBlur={onCommit} /></label><div className="property-toggles"><button className={item.bold ? "active" : ""} onClick={() => onChange({ bold: !item.bold })}>B</button><button className={item.italic ? "active" : ""} onClick={() => onChange({ italic: !item.italic })}>I</button><button className={item.underline ? "active" : ""} onClick={() => onChange({ underline: !item.underline })}>U</button></div></>}<label>{t.color}<input type="color" value={item.color ?? "#FF4FA3"} onChange={(event) => set("color", event.target.value)} onBlur={onCommit} /></label>{!["draw", "line", "arrow", "signature", "image"].includes(item.type) && <label>{t.fill}<input type="color" value={item.fillColor ?? "#000000"} onChange={(event) => set("fillColor", event.target.value)} onBlur={onCommit} /></label>}<label>{t.opacity}<input type="range" min=".1" max="1" step=".05" value={item.opacity ?? 1} onChange={(event) => set("opacity", Number(event.target.value))} onPointerUp={onCommit} /></label><label>{t.width}<input type="number" min="8" value={Math.round(Math.abs(item.width ?? 130))} onChange={(event) => set("width", Number(event.target.value))} onBlur={onCommit} /></label><label>{t.height}<input type="number" min="8" value={Math.round(Math.abs(item.height ?? 32))} onChange={(event) => set("height", Number(event.target.value))} onBlur={onCommit} /></label><button className="editor-delete" onClick={onDelete}>{t.deletePage.replace(" page", "")}</button><label className="font-inline">{t.font}<input type="file" accept=".ttf,.otf,font/ttf,font/otf" onChange={onFont} /><small>{t.fontHint}</small></label></div>; }

function ElementList({ items, allItems, selectedId, onSelect, onMutate }: { items: PdfEditorElement[]; allItems: PdfEditorElement[]; selectedId: string | null; onSelect: (id: string) => void; onMutate: (items: PdfEditorElement[]) => void }) { return <div className="element-list">{items.length ? items.map((item) => <div key={item.id} className={item.id === selectedId ? "active" : ""}><button onClick={() => onSelect(item.id)}>{item.label ?? item.type}</button><button onClick={() => onMutate(allItems.map((value) => value.id === item.id ? { ...value, visible: value.visible === false } : value))}>{item.visible === false ? "◌" : "●"}</button><button onClick={() => onMutate(allItems.map((value) => value.id === item.id ? { ...value, locked: !value.locked } : value))}>{item.locked ? "🔒" : "🔓"}</button><button onClick={() => onMutate(removeElement(allItems, item.id))}>×</button></div>) : <p>No added elements on this page.</p>}</div>; }

function EditorThumbnail({ pdf, page, index, active, onClick, onDragStart, onDrop, label }: { pdf: PdfJsDocument; page: EditorPage; index: number; active: boolean; onClick: () => void; onDragStart: (event: DragEvent<HTMLButtonElement>) => void; onDrop: (event: DragEvent<HTMLButtonElement>) => void; label: string }) { const canvas = useRef<HTMLCanvasElement>(null); useEffect(() => { let cancelled = false; void (async () => { const source = await pdf.getPage(page.sourceIndex + 1); const viewport = source.getViewport({ scale: .16, rotation: page.rotation }); if (cancelled || !canvas.current) return; canvas.current.width = viewport.width; canvas.current.height = viewport.height; await source.render({ canvasContext: canvas.current.getContext("2d")!, viewport }).promise; })(); return () => { cancelled = true; }; }, [pdf, page]); return <button draggable className={active ? "active" : ""} onClick={onClick} onDragStart={onDragStart} onDragOver={(event) => event.preventDefault()} onDrop={onDrop}><canvas ref={canvas} /><span>{label} · {index + 1}</span></button>; }
