"use client";
import { useState } from "react";
import type { Tool } from "@/lib/tools";
import { usePreferences } from "@/components/preferences";
export function DocumentConverter({ tool }: { tool: Tool }) {
  const { t } = usePreferences(); const [file, setFile] = useState<File | null>(null); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false); const wordToPdf = tool.slug === "word-to-pdf";
  const convert = async () => { if (!file) return; setBusy(true); setStatus(""); try { if (wordToPdf) await convertWordToPdf(file, setStatus, t); else await convertPdfToWord(file, setStatus, t); } catch { setStatus(t("We could not convert this file. Please try a standard DOCX or text-based PDF.", "无法转换此文件。请尝试标准 DOCX 或含有可选中文本的 PDF。")); } finally { setBusy(false); } };
  return <section className="workspace file-workspace"><div className="file-drop"><input id="document-file" type="file" accept={wordToPdf ? ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" : ".pdf,application/pdf"} onChange={(event) => setFile(event.target.files?.[0] || null)} /><label htmlFor="document-file"><strong>{file ? file.name : t(wordToPdf ? "Choose a DOCX file" : "Choose a PDF file", wordToPdf ? "选择 DOCX 文件" : "选择 PDF 文件")}</strong><span>{t("Your file stays in this browser.", "文件只会保留在此浏览器中。")}</span></label></div><button className="primary convert-button" type="button" onClick={convert} disabled={!file || busy}>{busy ? t("Converting…", "正在转换…") : t(wordToPdf ? "Convert to PDF" : "Convert to Word", wordToPdf ? "转换为 PDF" : "转换为 Word")}</button><p className="status" aria-live="polite">{status || t("Text-focused conversion. Complex formatting, tables and images may change.", "此版本以文本转换为主；复杂排版、表格和图片可能发生变化。")}</p></section>;
}
async function convertWordToPdf(file: File, setStatus: (value: string) => void, t: (en: string, zh: string) => string) { const mammoth = await import("mammoth"); const { jsPDF } = await import("jspdf"); const result = await mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() }); const pdf = new jsPDF({ unit: "pt", format: "a4" }); const lines = pdf.splitTextToSize(result.value || " ", 515); let y = 56; lines.forEach((line: string) => { if (y > 786) { pdf.addPage(); y = 56; } pdf.text(line, 40, y); y += 16; }); pdf.save(`${file.name.replace(/\.docx$/i, "")}.pdf`); setStatus(t("Your PDF download has started.", "PDF 下载已开始。")); }
async function convertPdfToWord(file: File, setStatus: (value: string) => void, t: (en: string, zh: string) => string) { const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs"); const { Document, Packer, Paragraph } = await import("docx"); const pdf = await pdfjs.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise; const paragraphs: InstanceType<typeof Paragraph>[] = []; for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber += 1) { const page = await pdf.getPage(pageNumber); const content = await page.getTextContent(); const text = content.items.map((item) => "str" in item ? item.str : "").join(" ").trim(); paragraphs.push(new Paragraph({ text: text || " " })); } const output = await Packer.toBlob(new Document({ sections: [{ children: paragraphs }] })); download(output, `${file.name.replace(/\.pdf$/i, "")}.docx`); setStatus(t("Your Word document download has started.", "Word 文档下载已开始。")); }
function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
