"use client";
import { useState } from "react";
import type { Tool } from "@/lib/tools";
import { usePreferences } from "@/components/preferences";
const converterUrl = process.env.NEXT_PUBLIC_CONVERTER_API_URL;
export function DocumentConverter({ tool }: { tool: Tool }) { const { t } = usePreferences(); const [file, setFile] = useState<File | null>(null); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false); const wordToPdf = tool.slug === "word-to-pdf";
  const convert = async () => { if (!file || !converterUrl) { setStatus(t("The production converter is not configured yet.", "生产转换服务尚未配置。")); return; } setBusy(true); setStatus(""); try { const action = tool.slug; const tokenResponse = await fetch("/api/converter-token", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); if (!tokenResponse.ok) throw new Error(); const { token } = await tokenResponse.json(); const form = new FormData(); form.append("file", file); const response = await fetch(`${converterUrl}/convert/${action}`, { method: "POST", headers: { "X-Converter-Token": token }, body: form }); if (!response.ok) throw new Error(); const blob = await response.blob(); const extension = wordToPdf ? "pdf" : "docx"; download(blob, `${file.name.replace(/\.[^.]+$/, "")}.${extension}`); setStatus(t("Your download has started.", "下载已开始。")); } catch { setStatus(t("We could not convert this file. Please try again or choose another file.", "无法转换此文件，请重试或选择其他文件。")); } finally { setBusy(false); } };
  return <section className="workspace file-workspace"><div className="file-drop"><input id="document-file" type="file" accept={wordToPdf ? ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" : ".pdf,application/pdf"} onChange={(event) => setFile(event.target.files?.[0] || null)} /><label htmlFor="document-file"><strong>{file ? file.name : t(wordToPdf ? "Choose a DOCX file" : "Choose a PDF file", wordToPdf ? "选择 DOCX 文件" : "选择 PDF 文件")}</strong><span>{t("Your file is converted securely and deleted after processing.", "文件会被安全转换，并在处理后删除。")}</span></label></div><button className="primary convert-button" type="button" onClick={convert} disabled={!file || busy}>{busy ? t("Converting…", "正在转换…") : t(wordToPdf ? "Convert to PDF" : "Convert to Word", wordToPdf ? "转换为 PDF" : "转换为 Word")}</button><p className="status" aria-live="polite">{status || t("PDF to Word preserves each PDF page visually. The resulting document is not intended for editing.", "PDF 转 Word 会视觉保留每一页；生成的文档不以编辑为目的。")}</p></section>; }
function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
