"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import { usePreferences } from "@/components/preferences";
import type { Tool } from "@/lib/tools";
const chinese: Record<string, [string, string, string]> = { "word-counter":["字数统计", "实时统计字数、字符数、句子和阅读时长。", "文本"], "character-counter":["字符统计", "实时统计字符、字数和行数。", "文本"], "case-converter":["大小写转换", "转换为大写、camelCase、snake_case 等格式。", "文本"], "json-formatter":["JSON 格式化", "即时格式化、压缩和验证 JSON。", "开发者"], "json-validator":["JSON 验证器", "检查 JSON 是否有效，并格式化正确的 JSON。", "开发者"], "base64":["Base64 编码 / 解码", "安全地将文本编码为 Base64 或解码。", "编码"] };
export function ToolDirectory({ tools }: { tools: Tool[] }) { const params = useSearchParams(); const { locale, t } = usePreferences(); const query = params.get("q") || ""; const [category, setCategory] = useState("All Tools"); const categories = ["All Tools", "Text", "Developer", "Encoding"]; const label = (categoryName: string) => t(categoryName, ({ "All Tools":"所有工具", Text:"文本", Developer:"开发者", Encoding:"编码" }[categoryName] || categoryName));
  const filtered = tools.filter((tool) => (category === "All Tools" || tool.category === category) && [tool.name, tool.description, ...tool.keywords, ...(chinese[tool.slug] || [])].join(" ").toLowerCase().includes(query.toLowerCase()));
  return <section className="directory" aria-labelledby="tools-heading"><div className="filters" role="tablist" aria-label={t("Tool categories", "工具分类")}>{categories.map((item) => <button key={item} id={item.toLowerCase().replace(" ", "-")} className={category === item ? "active" : ""} onClick={() => setCategory(item)} type="button">{label(item)}</button>)}</div><div className="directory-heading"><div><p className="eyebrow">{label(category).toUpperCase()}</p><h2 id="tools-heading">{t("Useful tools, ready when you are.", "实用工具，随时为你准备。")}</h2></div><p>{filtered.length} {t(filtered.length === 1 ? "tool available" : "tools available", filtered.length === 1 ? "个工具可用" : "个工具可用")}</p></div><div className="tool-grid">{filtered.map((tool) => { const content = locale === "zh" ? chinese[tool.slug] : undefined; return <Link className="tool-card" href={`/tools/${tool.slug}`} key={tool.slug}><span className="tool-icon" aria-hidden="true">{tool.icon}</span><span className="tool-card-content"><strong>{content?.[0] || tool.name}</strong><span>{content?.[1] || tool.description}</span><small>{content?.[2] || tool.category}</small></span><span className="arrow" aria-hidden="true">→</span></Link>; })}</div>{!filtered.length && <p className="empty">{t("No matching tools yet. Try a different search.", "暂未找到匹配工具，请尝试其他搜索词。")}</p>}</section>; }
